export const REFERENCE_PREFIX = 'TX';
export const REFERENCE_RANDOM_LENGTH = 6;
export const REFERENCE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export const REFERENCE_UTC_OFFSET_HOURS = -5; // America/Bogota, no DST
export const REFERENCE_MAX_ATTEMPTS = 3;
